### ISSUE TITLE
Value Error: Steps arugument

### ISSUE THREAD

**Issue by Zawan-uts** [aamini/introtodeeplearning_labs#20] opened 2019-02-20 01:30 UTC
Hi i get error from this line in lab 1.
`dense_layer = Dense(n_output_nodes, input_shape=(n_input_nodes,),activation='sigmoid')`

Error; 

> ValueError: When using data tensors as input to a model, you should specify the `steps` argument.

**Comment by apsoleimany** [comment] 2019-02-20 05:47
I'm not able to reproduce this, what TF version are you running?

**Comment by aamini** [comment] 2019-03-01 18:39
Closing since the issue is not reproducible when running the correct version of tensorflow

**Closed by aamini** 2019-03-01 18:39 UTC
