### ISSUE TITLE
Docker images pull error

### ISSUE THREAD

**Issue by ytzhao** [aamini/introtodeeplearning_labs#16] opened 2018-04-26 02:35 UTC
Hi amini, 
I'm trying to pull the docker images by this link [DockerHub](https://hub.docker.com/r/mit6s191/iap2018/), it seems that there're some problems. I try `docker pull mit6s191/iap2018` in terminal, it gives me this message:
```bash
Using default tag: latest
Error response from daemon: manifest for mit6s191/iap2018:latest not found
```
then, I use `docker pull mit6s191/iap2018:labs`, it shows:
```bash
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/48/48db1fb4c0b5d8aeb65b499c0623b057f6b50f93eed0e9cfb3f963b0c12a74db/data?Expires=1524752941&Signature=AKuwnCd69y-fs0NlLjQnAlBoUhbht-gWbIYIoIESf7dERzjlkeejUndYC1QCnEhjjlhZAvv2NWQFWEf-Efc6noGUV9hK4QRVaQqO23zRKRrqarTWVMLj5LQX4X1Qikze5YEXy4VqdNm5t88WRQsfDvsPHHDmKx6vqA2V4VgVDP8_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
```
Could you please help to address this problem? Thank you.

**Comment by aamini** [comment] 2018-04-26 05:57
I'm not able to reproduce your error on my machine. Is there a reason why you are running `docker pull`? What happens when you simply run `docker run ...`?

**Comment by ytzhao** [comment] 2018-04-27 03:16
Hi amini, I use `docker pull` to set up the environment for the labs. My docker version is `Server Version: 18.03.0-ce` on `Ubuntu 16.04`. When I simply run `docker run ...`, it gives me back this message:
```bash
docker: invalid reference format.
See 'docker run --help'.
```
And by the way, I pulled other docker images and run successfully, e.g `ufoym/deepo` by `docker pull` and `docker run`. Or probably there's something wrong with my network. I've already installed `tensorflow-gpu 1.4.1` and `opencv 3.4.1` by `anaconda`. So if I would like to do these labs, is this `tensorflow` version ok or not?

**Comment by ytzhao** [comment] 2018-04-27 03:30
Whooops, I misunderstood. It seems have the same error I encountered before.
```bash
$ docker run -p 8888:8888 -p 6006:6006 -v /media/ytzhao/olala/introtodeeplearning_labs:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs
Unable to find image 'mit6s191/iap2018:labs' locally
labs: Pulling from mit6s191/iap2018
1be7f2b886e8: Downloading [==================================>                ]  29.41MB/42.86MB
6fbc4a21b806: Pulling fs layer 
c71a6f8e1378: Pulling fs layer 
4be3072e5a37: Waiting 
06c6d2f59700: Waiting 
6a99deb058d4: Waiting 
416834ad7c80: Waiting 
5d9220d4de72: Waiting 
79b4122d5e5e: Waiting 
c0532cf95a31: Waiting 
22a2cf563723: Waiting 
354ea97a78e6: Waiting 
dda0fcda00bd: Waiting 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/48/48db1fb4c0b5d8aeb65b499c0623b057f6b50f93eed0e9cfb3f963b0c12a74db/data?Expires=1524842883&Signature=BJYIcpPy2wa1JeiDmyVtlHlJvbTpbMfYDIu9-wn-JjSNZPrJC1z~i6QU3y-MMOwxPVeDN7tibHxc7YNtM1LEFhXesMrN5pdwAdzOI7a9mWaH3WTpELLBqDke4lDk3iyEMzOfC0EQTPNGGoMTD7af0Ms2iYzo4YJOcfVliVKXahk_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.
See 'docker run --help'.
```

**Comment by aamini** [comment] 2018-04-27 03:32
Hmm that is interesting, I'm not immediately sure of the reason. Could you try running locally on your machine since you already have tensorflow installed?

**Comment by ytzhao** [comment] 2018-04-27 03:37
Yeap, I'll try to do these labs without this docker image and give you the feedback soon. Thanks :)

**Comment by ksskreddy** [comment] 2019-01-07 17:42
`docker pull mit6s191/iap2018`
This command is not working 

Instead  I used 
`docker pull mit6s191/iap2018:labs  `
for pulling the labs image

**Comment by aamini** [comment] 2019-01-27 06:07
Closing this issue since we are releasing new labs which do not use docker and wont have this problem.

**Closed by aamini** 2019-01-27 06:07 UTC
